name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Compile Extension
        uses: cli/gh-extension-precompile@v1
        with:
          go_version_file: "go.mod"
